apiVersion: v1
kind: Service
metadata:
  name: linkshort
  labels:
    app: linkshort
spec:
  type: ClusterIP
  selector:
    app: linkshort
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
